# Generated by Django 4.1.7 on 2023-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=100)),
                ('pizza_price', models.IntegerField()),
                ('pizza_type', models.CharField(max_length=130)),
                ('pizza_size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
