# Generated by Django 4.1.7 on 2023-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A5stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzastock',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
